# Generated by Django 5.0.2 on 2024-05-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindOfInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='insurance',
            name='kind_of_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni_app.kindofinsurance'),
        ),
    ]
