# Generated by Django 5.0.2 on 2024-05-17 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0002_kindofinsurance_alter_insurance_kind_of_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni_app.customer'),
        ),
    ]
