# Generated by Django 5.0.2 on 2024-05-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0003_insurance_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
