# Generated by Django 5.0.2 on 2024-05-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0005_alter_insurance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
