# Generated by Django 5.0.2 on 2024-05-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0009_alter_customer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.AddField(
            model_name='customer',
            name='assigned_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
