# Generated by Django 5.0.2 on 2024-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0010_remove_customer_created_by_customer_assigned_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
