# Generated by Django 5.0.2 on 2024-05-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0011_customer_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
    ]
