# Generated by Django 5.0.2 on 2024-05-23 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_pojisteni_app', '0013_customer_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidence_pojisteni_app.userprofile'),
        ),
    ]
